### PR TITLE
Update Routing.qml

### PR DESCRIPTION
**Pull request by GNUuser**

### CODE REVIEW

**Comment by Karry** [comment]
I'm not native English speaker, but I don't think that this phrase is widely used... Or not? Google is using "Reverse starting point and destination" in theirs maps... 
  
obrazek

**Comment by GNUuser** [comment]
I am seeing that in Sailfish the applications are abusing the native option of sailfish which is the "pulley menu", I am not talking about OSMScount but what I mean is that sometimes an icon is better to express an action. So maybe an icon with " 2 arrows inverted " is better to say "Exchage route" or " Whatever ".
Another thing. The word strings used by Google are from Google, and we are other things with high capacities so as not to depend on copying and pasting.

**Comment by GNUuser** [comment]
To be honest  i am not a native English too, but I student english every day. But "Swap start and target"  not sound or clear good to me, so I trying to change and contribute for a better phrase. 
I am seeing that in sailfish the applications are abusing the native option of sailfish which is the "pulley menu", I am not talking about OSMScount but what I mean is that sometimes an icon is better to express an action. So maybe an icon with 2 arrows is better to say "Exchage route" or "Whatever".
Another thing. The word strings used by Google are from Google, and we are other things with high capacities so as not to depend on copying and pasting.

**Comment by Karry** [comment]
> But "Swap start and target" not sound or clear good to me...

Ok, what about "Reverse route" or "Reverse direction" ? Word "Exchange" is not accurate from my point of view...

**Comment by GNUuser** [comment]
Yeah "Reverse route" is fine .

**Comment by GNUuser** [comment]
Hey @karry what about "Reverse point" ?? = ) --------> I'm kidding.

**Pull request closed without merging**
