### PR TITLE
Update es.ts

### PR DESCRIPTION
**Pull request by GNUuser**

### CODE REVIEW

**Comment by Karry** [comment]
Tanks.

**Comment by GNUuser** [comment]
> Tanks.

when new release? =  )

**Comment by Karry** [comment]
I want to implement collection sorting. Then release new version with all UI improvents to the end of this week.

**Comment by GNUuser** [comment]
> I want to implement collection sorting. Then release new version with all UI improvents to the end of this week.

Wow I can not wait for that release! Thank You.

**Comment by Karry** [comment]
I will not make it this week. I will have to release it later. I hope to the end of June.

**Pull request merged**
