### PR TITLE
Create sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Hi,

Swedish translation if wanted. Some translation strings not working/missing...

screen-20161217-002
screen-20161217-003

### CODE REVIEW

**Comment by Karry** [comment]
Hi Åke. Thanks for it! I added missing string definitions, can you please rebase your branch (with my master branch), execute `lupdate osmscout-sailfish.pro -ts translations/sv.ts` and update translations? 

Btw, I added translators to "About" page and add your name there ;-)

If you want to translate country list, you can create another merge request with extension of this file: https://github.com/Karry/osmscout-scripts/blob/master/web/database.sql#L76 Country list is provided by server (clients send locale with request). 

Thanks

**Comment by eson57** [comment]
Ok, translation updated.

**Comment by Karry** [comment]
New translation have to be added t CMakeLists.txt. I will add there. "Search" term don't work at all, it seems that first item of the menu is initialized before translator...

**Comment by Karry** [comment]
Thanks for this merge request!

**Comment by eson57** [comment]
And thanks for the app. I'll watch and update.

**Pull request merged**
