### PR TITLE
Updating the app icon

### PR DESCRIPTION
**Pull request by arustg**

### CODE REVIEW

**Comment by Karry** [comment]
Thank you for the proposal. Can you also share vector variant please? Original is here: https://github.com/Karry/osmscout-sailfish/blob/master/graphics/harbour-osmscout.svg

I'm not sure if I will use it. My first impression is that these tin contour lines don't fit to simple shapes used by official Sailfish OS icons... I will try to use your icons on my phone for few days...

**Comment by arustg** [comment]
Ок, I am glad to help - https://github.com/arustg/osmscout-sailfish/blob/master/graphics/harbour-osmscout.svg

**Comment by Karry** [comment]
Sorry, for such late reply. I decided to use different style for the new icon... https://github.com/Karry/osmscout-sailfish/blob/master/graphics/harbour-osmscout-v2.svg

Thank you for proposal anyway.

**Comment by arustg** [comment]
Originally )

**Pull request closed without merging**
