### PR TITLE
Update es.ts

### PR DESCRIPTION
**Pull request by Caballlero**
Some suggest: Line: 660 Accomodation > Lodging Line: 636 Cafe > Cafeteria
Hello karry can you give more info about it?

### CODE REVIEW

**Comment by Caballlero** [comment]
Some suggest: Line: 660 Accomodation > Lodging  Line: 636 Cafe > Cafeteria
Hello karry can you give more info about it?

**Comment by Karry** [comment]
Thank you for fast translation. I added list of POI types to search page, it is visible when search string is empty. When you select it, it display nearest objects with this type. 

For accomodation are displayed near objects of these OSM types:
 * [tourism == hotel](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dhotel)
 * [tourism == hostel](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dhostel)
 * [tourism == motel](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dmotel)
 * [tourism == alpine_hut](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dalpine_hut)

For cafe is displayed objects (nodes or buildings) with [amenity == cafe](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcafe)

screenshot_20180226_001

**Comment by Caballlero** [comment]
Looking really nice @Karry. when release?
The word 'Accomodation' has to been changed to 'Lodging' it is more good I think so. I just helping you.

**Comment by Karry** [comment]
Thank you, but for hotel/hostel is "accomodation" more accurate from my point of view - [Accommodation vs Lodging - What's the difference?](https://wikidiff.com/accommodation/lodging). But I am not very good with English. I will ask my colleagues to be sure with that...

I will release it next week probably. I want to improve database management ( https://github.com/Karry/osmscout-sailfish/issues/73 ) with next release too, when work duties allows.

**Pull request merged**
