### PR TITLE
Update es.ts

### PR DESCRIPTION
**Pull request by Caballlero**
I had problem to undestand line 542

### CODE REVIEW

**Comment by Karry** [comment]
Hi Carlos. This route step is used when one named way is ending and continue with different name (or different reference number), but you should continue straight on. This route command is not so useful, probably no voice command will be assigned with it, but it will see in future testing when navigation will be done.

**Comment by Karry** [comment]
Another note, please don't translate html tags, like `&lt;strong&gt;`. I added two variants of route steps - one is formatted with few html tags and second is simple plain text. Html tag `strong` just identify part of command that should be displayed bold...

obrazek

I plan to use detailed, formatted commands in detailed list and simplified variant in map overlay...

**Comment by Karry** [comment]
Anyway, thank you for fast translations :-) I plan to release new version soon with translatable route steps, but still without navigation.

**Comment by Caballlero** [comment]
Thanks I will fix that.
Thanks too for developing this nice app. You are the best of this :  )

**Comment by Caballlero** [comment]
thank you Karry to merge/fix my PR.

**Pull request merged**
